version: "3"
services:
  app:
    image: ghcr.io/zemoso-int/bootcamp_27_bd/bc27-green-commute-${{ steps.extract_branch.outputs.branch }}:${{ github.run_id }}
    restart: always
    ports:
      - "3000:80" #docker run -p 3000:80 --link jsondb:jsondb app1
    depends_on:
      jsondb:
        condition: service_started
  jsondb:
    build: ghcr.io/zemoso-int/bootcamp_27_bd/bc27-mock-server-${{ steps.extract_branch.outputs.branch }}:${{ github.run_id }}  #docker run -p 8081:8081 jsondb
    ports: 
      - "8081:8081"
    volumes:
      - ./mock-server/db.json:/data/db.json

  